### ISSUE TITLE
Error: fail tx invalid signature

### ISSUE THREAD

**Issue by roccomuso** [icon-project/icon-sdk-js#19]
I got this error:

`{"jsonrpc":"2.0","error":{"code":-32600,"message":"fail tx invalid signature"},"id":1583417144718}`

 when trying to broadcast this:

```js
{ to: 'hx9cce391eba4280ad3a67be1c34b60b25706c6084',
  from: 'hxbede3b05a3b35ccb833489b29ce6ddfeb76899e2',
  stepLimit: '0x186a0',
  nid: '0x1',
  version: '0x3',
  timestamp: '0x5a01c084249e1',
  value: '0xde0b6b3a7640000',
  nonce: '0x238',
  signature:
   'IodkVvIJ2mZ8awb1Bs1ovQpt5Fmd7i7qWXe3/FSTE11rmMcko28pq41JM1dx43+fEyvWwD+OS4y6B/moJQXuJwE=' }
```

**Comment by Spl3en** [comment]
Solved:
The 'from' field broadcasted in that transaction was different from the wallet address signing this transaction, hence the "invalid signature" error.

**Comment by hoang-dao** [comment]
For anyone who still got this issue even after trying @Spl3en 's solution, this issue can also be caused by missing or passing empty params when building transaction to deploy contract. Basically, the following code using `icon-sdk-js` will cause the problem:
```
const transaction = new DeployTransactionBuilder()
      ...
      .params(undefined)
      .build();
```
same problem when using the above code without calling `.params()` function.

=> should check `params` (or at least set it an empty object `.params({})`) before building transaction.

The error message seems to be confusing since there's nothing related to invalid signature at all.

**Comment by 9cat** [comment]
also the wrong nonce vaule
